export const CHANGE_GRAPHDATA = 'change_graphData';
export const SET_GRAPHDATAMAP = 'set_graphDataMap';
export const DELETE_GRAPHDATAMAP = 'delete_graphDataMap';
export const CLEAR_GRAPHDATAMAP = 'clear_graphDataMap';
export const CHANGE_CURRENTEDITINGBLOCKID = 'change_current_editing_block_id';
export const SYNCHRO_GRAPHDATAMAP = 'synchro_graphDataMap';
export const CHANGE_CHECKEDGRAPHBLOCKID = 'change_checkedGraphBlockId';
export const CHANGE_EDITORBLOCKPYTHONCODE = 'change_editorBlockPythonCode';
export const CHANGE_PROCESSTREE = 'change_processTree';
export const CHANGE_CHECKEDTREENODE = 'change_checkedTreeNode';
export const CHANGE_CURRENTPROJECT = 'change_currentProject';
export const SYNCHRO_GRAPHDATATOPROCESSTREE = 'synchro_graphDataToProcessTree';
export const CHANGE_CURRENTEDITINGPROCESSID = 'currentEditingProcessId';
export const RESET_ALLGRAPHEDITDATA = 'reset_allGraphEditData';
export const RESET_GRAPHERITORALLDATA = 'reset_grapheditoralldata';
export const CHANGE_MODULE_TREE = 'change_module_tree';
export const CHANGE_CHECKED_MODULE_TREE_NODE =
  'change_checked_module_tree_node';
export const CHANGE_TREE_TAB = 'change_tree_tab';
